name: main-check
on: 
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name : install dependencies 
        run: npm install
      - name : run tests 
        run: make test
      - name : run linter
        run : make lint
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
